spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postflow
    username: ${DB_USERNAME:postflow}
    password: ${DB_PASSWORD:postflow}

storage:
  local:
    base-path: ./var/storage
    public-base-url: http://localhost:8080/files
