-- 멀티채널 동시발행(증분2): 한 글 → 여러 채널(post_targets). 채널별 상태/결과를 개별 추적(부분 실패 허용).
CREATE TABLE post_targets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id           BIGINT NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    social_account_id BIGINT NOT NULL REFERENCES social_accounts (id) ON DELETE CASCADE,
    status            VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    platform_post_id  VARCHAR(255),
    error_message     VARCHAR(1000),
    retry_count       INTEGER NOT NULL DEFAULT 0,
    published_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_post_targets_post_id ON post_targets (post_id);

-- 기존 글 백필: social_account_id가 지정된 글은 그 채널로 타겟 1건 생성(상태·플랫폼글id 이관).
INSERT INTO post_targets (post_id, social_account_id, status, platform_post_id, published_at, retry_count)
SELECT p.id, p.social_account_id,
       CASE p.status
           WHEN 'PUBLISHED' THEN 'PUBLISHED'
           WHEN 'FAILED' THEN 'FAILED'
           WHEN 'RECONNECT_REQUIRED' THEN 'RECONNECT_REQUIRED'
           ELSE 'PENDING'
       END,
       p.threads_media_id, p.published_at, COALESCE(p.retry_count, 0)
FROM posts p
WHERE p.social_account_id IS NOT NULL AND p.status <> 'DELETED';
